### ISSUE TITLE
Unify config for runtime/tools

### ISSUE THREAD

**Issue by dmaretskyi** [dxos/cli#350]
## Single schema for all DXOS related configs: runtime and publish

Schema defintion is in `dxos/protocols/packages/common/proto/src/proto/dxos/config.proto`

Example of how it would look in yaml:

```yaml
version: 1

module:
  name: dxos:app.tasks
  type: dxos:type.app
  version: 1.2.3 # Loaded from package.json

  author: DXOS.org
  license: GPL-3.0
  description: Braneframe
  repository: 'https://github.com/dxos/frame-app'

  record:
    app: # Same as dxos.type.App (from DXNS)
      contentType:
        - 'dxos:type.chess.board'

build:
  command: npm run build

runtime:
  services:
    signal:
      server: "wss://apollo3.kube.moon.dxos.network/dxos/signal"
    dxns:
      server: "https://apollo3.kube.moon.dxos.network/dxos/wns/api"
  
  client:
    storage:
      persistent: true

  bot:
    factory:
      id: 123
  
  props:
    title: "Tasks App"
```

## Config loading

Both apps at runtime and cli tools use @dxos/config package to load the config.

In general case it has an array of "config sources": yaml files, remote kube config, cli profile to load config from.
Those are then merged into a single config.

## Config files:

- `dx.yml` Deploy configuration + runtime defaults
- `dx-dev.yml` Dev overrides for runtime configuration

## Tasks

- [ ] Update config protos with new design
- [ ] Use @dxos/config to load config in CLI extensions (app/bot publish)
